version: '2'
services:
    apache:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - http_proxy=$http_proxy
                - no_proxy=$no_proxy
        environment:
            - http_proxy=$http_proxy
            - no_proxy=$no_proxy
        volumes:
            - ./:/var/www/html
        ports:
            - "8070:80"
